name: "Python Release Action"
description: "An action to release Python packages."
inputs:
  command:
    description: "The command to run (release or publish)"
    required: false
    default: "changelog"
  changelog-args:
    description: "Additional arguments for the changelog command"
    required: false
    default: ""
  tag-args:
    description: "Additional arguments for the tag command"
    required: false
    default: ""
  bump-args:
    description: "Additional arguments for the bump command"
    required: false
    default: ""
  push:
    description: |
      Whether to push changes to the remote repository.
      Note: This requires appropriate permissions.
    required: false
    default: "false"
  push-branch:
    description: "The branch to push changes to"
    required: false
    default: "main"
  git-username:
    description: "Git username for committing changes"
    required: false
    default: "github-actions[bot]"
  git-email:
    description: "Git email for committing changes"
    required: false
    default: "github-actions[bot]@users.noreply.github.com"
  github-token:
    description: "GitHub token for authentication"
    required: true
    default: "${{ github.token }}"
outputs:
  old-version:
    description: "Old version"
    value: ${{ steps.bump.outputs.old-version }}
  new-version:
    description: "New version"
    value: ${{ steps.bump.outputs.new-version }}
runs:
  using: "composite"
  steps:
    - uses: jdx/mise-action@v3
    - name: "Check command"
      shell: "bash"
      env:
        GITHUB_TOKEN: ${{ inputs.github-token }}
      run: |
        valid_commands=("release" "publish")
        if [[ ! " ${valid_commands[@]} " =~ " ${{ inputs.command }} " ]]; then
          echo "Unknown command: ${{ inputs.command }}"
          exit 1
        fi
        git config --global user.name "${{ inputs.git-username }}"
        git config --global user.email "${{ inputs.git-email }}"
    - name: "Bump Version"
      id: bump
      shell: "bash"
      env:
        GITHUB_TOKEN: ${{ inputs.github-token }}
      run: |
        uv run --no-dev pyrelease bump ${{ inputs.bump-args }}
    - name: "Create Tag"
      shell: "bash"
      env:
        GITHUB_TOKEN: ${{ inputs.github-token }}
      run: |
        uv run --no-dev pyrelease tag ${{ inputs.tag-args }}
    - name: "Generate Changelog"
      shell: "bash"
      env:
        GITHUB_TOKEN: ${{ inputs.github-token }}
      run: |
        uv run --no-dev pyrelease changelog \
          --from-ref="v${{ steps.bump.outputs.old-version }}" \
          --to-ref="v${{ steps.bump.outputs.new-version }}" \
          ${{ inputs.changelog-args }}
    - name: "Publish Release"
      if: ${{ inputs.command == 'publish' }}
      shell: "bash"
      env:
        GITHUB_TOKEN: ${{ inputs.github-token }}
      run: |
        uv publish
    - name: "Push Changes"
      if: ${{ inputs.push == 'true' && inputs.push-branch != '' }}
      shell: "bash"
      env:
        GITHUB_TOKEN: ${{ inputs.github-token }}
      run: |
        git push origin ${{ inputs.push-branch }} --tags
